/**
 * Upload-into-target-table importer.
 *
 * Given a target API connection (which has its schema already persisted
 * in the EO log — see `ingestConnectionSchema`) and a CSV/JSON file
 * dropped in by the user, parse the file, map columns to fields on the
 * target table, and emit per-record DEFs via the shared
 * event-sourced-ingest helper.
 *
 * Column matching strategy (in order):
 *   1. Exact match against a field's `internalName` (the post-mapping
 *      name the connection's `fieldMappings` produced). This is what the
 *      user actually sees in the data grid, so most exports will name
 *      columns this way.
 *   2. Case-insensitive match against the same `internalName`.
 *   3. Exact match against the `remoteFieldId` (Airtable `fld…`) for
 *      power users exporting raw.
 *   4. Exact match against the source field name (Airtable's display
 *      name before mapping).
 *
 * Columns that don't match any field are reported as `unmappedColumns`
 * — they're not silently dropped, the UI surfaces them so the user can
 * decide whether to rename and retry.
 *
 * Row id selection: per row, the first non-empty value among `id`,
 * `_id`, `ID`, `recordId`, `record_id` is used as the record id. If
 * none is present a content-hashed fallback id is generated so two
 * identical rows from the same import dedup against each other, but
 * row-to-source linkage is broken (we surface this in the result so the
 * UI can warn).
 */

import { useEoStore } from '../../store/eo-store';
import type { ApiConnectionConfig } from '../api-adapters/types';
import {
  DEFAULT_INGEST_AGENT,
  fieldSchemaTarget,
  ingestRemoteRecord,
  schemaTarget,
  type IngestRemoteRecordOutcome,
} from '../../ingestion/event-sourced-ingest';
import { stableStringify } from '../../ingestion/value-extract';
import type { ParsedRows } from './parse';

/** Persisted schema for a connection, as read back from EO state. */
interface PersistedSchema {
  baseName: string;
  tableName: string;
  tableId: string;
  fields: Array<{
    fieldId: string;
    name: string;
    type: string;
    /** Connection-internal name (post field-mapping). Resolved from the connection config. */
    internalName: string;
    options?: Record<string, unknown>;
  }>;
}

export interface ImportRecordsResult {
  outcomes: Record<IngestRemoteRecordOutcome, number>;
  /** Source columns that did not match any field on the target schema. */
  unmappedColumns: string[];
  /** Rows that had no usable id column; an autogenerated id was used. */
  rowsWithFallbackId: number;
  /** Total rows attempted. */
  rowsTotal: number;
}

/** Read the persisted schema for a connection from EO state. */
export async function loadPersistedSchema(
  config: ApiConnectionConfig,
): Promise<PersistedSchema | null> {
  const { getState, getStateByPrefix } = useEoStore.getState();
  const header = await getState(schemaTarget(config.connectionId));
  if (!header || !header.value || typeof header.value !== 'object') return null;
  const headerValue = header.value as Record<string, unknown>;

  const fieldStates = await getStateByPrefix(`${schemaTarget(config.connectionId)}.field.`);

  // Build a reverse field-mapping (remoteFieldId → internalName) from the
  // connection config so the importer can also accept internal names.
  const internalByRemote: Record<string, string> = {};
  for (const [remoteId, internalName] of Object.entries(config.fieldMappings)) {
    if (internalName) internalByRemote[remoteId] = internalName;
  }

  const fields: PersistedSchema['fields'] = [];
  for (const state of fieldStates) {
    if (!state.value || typeof state.value !== 'object') continue;
    const v = state.value as Record<string, unknown>;
    const fieldId = String(v.fieldId ?? '');
    if (!fieldId) continue;
    fields.push({
      fieldId,
      name: String(v.name ?? fieldId),
      type: String(v.type ?? 'unknown'),
      internalName: internalByRemote[fieldId] ?? String(v.name ?? fieldId),
      ...(v.options && typeof v.options === 'object'
        ? { options: v.options as Record<string, unknown> }
        : {}),
    });
  }

  return {
    baseName: String(headerValue.baseName ?? ''),
    tableName: String(headerValue.tableName ?? ''),
    tableId: String(headerValue.tableId ?? ''),
    fields,
  };
}

// ─── Column matching ────────────────────────────────────────────────────────

interface ColumnMatch {
  /** Source column header. */
  source: string;
  /** Resolved `internalName` on the target schema (post field-mapping). */
  internalName: string;
}

function matchColumns(
  columns: string[],
  schema: PersistedSchema,
): { matched: ColumnMatch[]; unmapped: string[] } {
  const matched: ColumnMatch[] = [];
  const unmapped: string[] = [];

  const byInternal = new Map<string, string>(); // internalName (lower) → internalName
  const byRemoteId = new Map<string, string>(); // fieldId → internalName
  const byRemoteName = new Map<string, string>(); // source name (lower) → internalName

  for (const f of schema.fields) {
    byInternal.set(f.internalName.toLowerCase(), f.internalName);
    byRemoteId.set(f.fieldId, f.internalName);
    byRemoteName.set(f.name.toLowerCase(), f.internalName);
  }

  for (const col of columns) {
    const trimmed = col.trim();
    const lower = trimmed.toLowerCase();
    const hit =
      byInternal.get(lower) ??
      byRemoteId.get(trimmed) ??
      byRemoteName.get(lower);
    if (hit) {
      matched.push({ source: col, internalName: hit });
    } else {
      unmapped.push(col);
    }
  }

  return { matched, unmapped };
}

// ─── Row id selection ───────────────────────────────────────────────────────

const ID_COLUMNS = ['id', '_id', 'ID', 'recordId', 'record_id'];

function pickRecordId(row: Record<string, unknown>): string | null {
  for (const key of ID_COLUMNS) {
    const v = row[key];
    if (v != null && v !== '') return String(v);
  }
  return null;
}

// ─── Type coercion ──────────────────────────────────────────────────────────

/**
 * Coerce a string cell from a CSV into a JS primitive when the target
 * field's type is one of the few we can losslessly convert. JSON inputs
 * are passed through unchanged.
 */
function coerceForType(value: unknown, type: string): unknown {
  if (typeof value !== 'string') return value;
  switch (type) {
    case 'number':
    case 'currency':
    case 'percent':
    case 'count':
    case 'autoNumber':
    case 'rating':
    case 'duration': {
      if (value.trim() === '') return null;
      const n = Number(value);
      return Number.isFinite(n) ? n : value;
    }
    case 'checkbox': {
      const lower = value.trim().toLowerCase();
      if (lower === 'true' || lower === '1' || lower === 'yes') return true;
      if (lower === 'false' || lower === '0' || lower === 'no' || lower === '') return false;
      return value;
    }
    case 'multipleRecordLinks':
    case 'multipleSelects':
    case 'multipleAttachments':
    case 'multipleLookupValues':
    case 'multipleCollaborators': {
      // Comma-separated lists. Trim each element; drop empties.
      return value
        .split(',')
        .map((s) => s.trim())
        .filter((s) => s.length > 0);
    }
    default:
      return value;
  }
}

// ─── Main importer ──────────────────────────────────────────────────────────

export async function importRecordsIntoConnection(
  config: ApiConnectionConfig,
  parsed: ParsedRows,
  opts: { agent?: string } = {},
): Promise<ImportRecordsResult> {
  const agent = opts.agent ?? DEFAULT_INGEST_AGENT;
  const schema = await loadPersistedSchema(config);
  if (!schema) {
    throw new Error(
      'Connection has no persisted schema. Save (or re-edit) the connection so its schema can be discovered before importing data into it.',
    );
  }

  const { matched, unmapped } = matchColumns(parsed.columns, schema);
  if (matched.length === 0) {
    throw new Error(
      `None of the file's columns (${parsed.columns.slice(0, 5).join(', ')}${
        parsed.columns.length > 5 ? '…' : ''
      }) matched fields on the target table "${schema.tableName}". ` +
        `Available fields: ${schema.fields.map((f) => f.internalName).slice(0, 5).join(', ')}${
          schema.fields.length > 5 ? '…' : ''
        }`,
    );
  }

  const typeByInternal = new Map<string, string>();
  for (const f of schema.fields) typeByInternal.set(f.internalName, f.type);

  const outcomes: Record<IngestRemoteRecordOutcome, number> = {
    tombstoned: 0,
    ins_emitted: 0,
    def_emitted: 0,
    no_change: 0,
    failed: 0,
  };
  let rowsWithFallbackId = 0;

  for (const row of parsed.rows) {
    const fields: Record<string, unknown> = {};
    for (const col of matched) {
      const raw = row[col.source];
      if (raw === undefined) continue;
      const type = typeByInternal.get(col.internalName) ?? 'unknown';
      fields[col.internalName] = coerceForType(raw, type);
    }

    let recordId = pickRecordId(row);
    if (!recordId) {
      // Stable fallback id derived from the row content. Two identical
      // rows will dedup; row-to-source linkage is lost.
      recordId = `import:${await sha1Hex(stableStringify(fields))}`;
      rowsWithFallbackId += 1;
    }

    const outcome = await ingestRemoteRecord({
      connectionId: config.connectionId,
      recordId,
      fields,
      lastModifiedAt: new Date().toISOString(),
      agent,
    });
    outcomes[outcome] += 1;
  }

  return {
    outcomes,
    unmappedColumns: unmapped,
    rowsWithFallbackId,
    rowsTotal: parsed.rows.length,
  };
}

// ─── Helpers ────────────────────────────────────────────────────────────────

async function sha1Hex(input: string): Promise<string> {
  const data = new TextEncoder().encode(input);
  const digest = await crypto.subtle.digest('SHA-1', data);
  const bytes = new Uint8Array(digest);
  let hex = '';
  for (let i = 0; i < bytes.length; i++) {
    hex += bytes[i].toString(16).padStart(2, '0');
  }
  return hex;
}
